import { Content, Teachers, Categories, Languages } from 'types';

export const seed: Content[] = [
  {
    category: Categories.Movement,
    thumbnail: 'https://i.ytimg.com/vi/eT6eW4wWXeI/hqdefault.jpg',
    title: 'Movement Video 1',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Nicole,
    language: Languages.En,
  },
  {
    category: Categories.Movement,
    thumbnail: 'https://i.ytimg.com/vi/M7rlUFTwr-c/hqdefault.jpg',
    title: 'Movement Video 2',
    video: 'https://www.youtube.com/watch?v=M7rlUFTwr-c',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Mike,
    language: Languages.En,
  },
  {
    category: Categories.Movement,
    thumbnail: 'https://i.ytimg.com/vi/wlS8efuOpZg/hqdefault.jpg',
    title: 'Movement Video 3',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Nicole,
    language: Languages.Es,
  },
  {
    category: Categories.Movement,
    thumbnail: 'https://i.ytimg.com/vi/eT6eW4wWXeI/hqdefault.jpg',
    title: 'Movement Video 4',
    video: 'https://www.youtube.com/watch?v=M7rlUFTwr-c',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Mike,
    language: Languages.En,
  },
  {
    category: Categories.Movement,
    thumbnail: 'https://i.ytimg.com/vi/M7rlUFTwr-c/hqdefault.jpg',
    title: 'Movement Video 5',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Nicole,
    language: Languages.Es,
  },
  {
    category: Categories.Meditation,
    thumbnail: 'https://i.ytimg.com/vi/wlS8efuOpZg/hqdefault.jpg',
    title: 'Meditation Video 1',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Steph,
    language: Languages.En,
  },
  {
    category: Categories.Meditation,
    thumbnail: 'https://i.ytimg.com/vi/eT6eW4wWXeI/hqdefault.jpg',
    title: 'Meditation Video 2',
    video: 'https://www.youtube.com/watch?v=M7rlUFTwr-c',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Mike,
    language: Languages.Es,
  },
  {
    category: Categories.Meditation,
    thumbnail: 'https://i.ytimg.com/vi/M7rlUFTwr-c/hqdefault.jpg',
    title: 'Meditation Video 3',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Steph,
    language: Languages.En,
  },
  {
    category: Categories.Meditation,
    thumbnail: 'https://i.ytimg.com/vi/M7rlUFTwr-c/hqdefault.jpg',
    title: 'Meditation Video 4',
    video: 'https://www.youtube.com/watch?v=M7rlUFTwr-c',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Mike,
    language: Languages.En,
  },
  {
    category: Categories.Meditation,
    thumbnail: 'https://i.ytimg.com/vi/eT6eW4wWXeI/hqdefault.jpg',
    title: 'Meditation Video 5',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Steph,
    language: Languages.En,
  },
];
