import { Content, Teachers, Categories, Languages } from 'types';

export const seed: Content[] = [
  {
    category: 'Movement',
    thumbnail: 'https://i.ytimg.com/vi/eT6eW4wWXeI/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCo0bPMhTsEvsVqPx5x3je3z3tT-A',
    title: 'Movement Video 1',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Nicole,
    language: Languages.En,
  },
  {
    category: 'Movement',
    thumbnail: 'https://i.ytimg.com/vi/M7rlUFTwr-c/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLA2KdjQGl6QswuY_m9kybhgABWM2g',
    title: 'Movement Video 2',
    video: 'https://www.youtube.com/watch?v=M7rlUFTwr-c',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Mike,
    language: Languages.En,
  },
  {
    category: 'Movement',
    thumbnail: 'https://i.ytimg.com/vi/wlS8efuOpZg/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBjrLfVEgWo3HDojPPrJIPg4hSMEQ',
    title: 'Movement Video 3',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Nicole,
    language: Languages.Es,
  },
  {
    category: 'Movement',
    thumbnail: 'https://i.ytimg.com/vi/eT6eW4wWXeI/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCo0bPMhTsEvsVqPx5x3je3z3tT-A'
    title: 'Movement Video 4',
    video: 'https://www.youtube.com/watch?v=M7rlUFTwr-c',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Mike,
    language: Languages.En,
  },
  {
    category: 'Movement',
    thumbnail: 'https://i.ytimg.com/vi/M7rlUFTwr-c/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLA2KdjQGl6QswuY_m9kybhgABWM2g',
    title: 'Movement Video 5',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Nicole,
    language: Languages.Es,
  },
  {
    category: 'Meditation',
    thumbnail: 'https://i.ytimg.com/vi/wlS8efuOpZg/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBjrLfVEgWo3HDojPPrJIPg4hSMEQ',
    title: 'Meditation Video 1',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Steph,
    language: Languages.En,
  },
  {
    category: 'Meditation',
    thumbnail: 'https://i.ytimg.com/vi/eT6eW4wWXeI/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCo0bPMhTsEvsVqPx5x3je3z3tT-A',
    title: 'Meditation Video 2',
    video: 'https://www.youtube.com/watch?v=M7rlUFTwr-c',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Mike,
    language: Languages.Es,
  },
  {
    category: 'Meditation',
    thumbnail: 'https://i.ytimg.com/vi/M7rlUFTwr-c/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLA2KdjQGl6QswuY_m9kybhgABWM2g',
    title: 'Meditation Video 3',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Steph,
    language: Languages.En,
  },
  {
    category: 'Meditation',
    title: 'Meditation Video 4',
    video: 'https://www.youtube.com/watch?v=M7rlUFTwr-c',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Mike,
    language: Languages.En,
  },
  {
    category: 'Meditation',
    thumbnail: 'https://i.ytimg.com/vi/eT6eW4wWXeI/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCo0bPMhTsEvsVqPx5x3je3z3tT-A',
    title: 'Meditation Video 5',
    video: 'https://www.youtube.com/watch?v=eT6eW4wWXeI',
    description: 'Lorem ipsum this is for kids ages 8-10.',
    teacher: Teachers.Steph,
    language: Languages.En,
  },
];
